name: todo_web
description: A simple Todo web app with Flutter
version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1               # ← 依存パッケージはここだけ

flutter:
  uses-material-design: true
