name: todo_web
description: A simple Todo web app with Flutter
version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  table_calendar: ^3.1.1
  flutter_localizations:          # ← これを追加
    sdk: flutter
  flutter_dotenv: ^5.1.0

flutter:
  uses-material-design: true
